/* 
*  DB Script Tool
*  Oracle - 2019-08-13 11:47:25
*  2019-08-13 11:40:51
*/ 
CREATE DATABASE E28D
   LOGFILE  E28D.log
   NATIONAL CHARACTER SET UTF8
   DATAFILE E28D.dbf
   AUTOEXTEND ON MAXSIZE 500MB;



/* 
*  SYO
*  SYO
*/ 
DROP TABLE SYO;
CREATE TABLE SYO (
    SYO NUMBER(1440) NOT NULL,
 CONSTRAINT PK_SYO PRIMARY KEY (SYO)
);

CREATE UNIQUE INDEX idx_SYO_SYO ON SYO (SYO);

CREATE SEQUENCE Seq_SYO_SYO INCREMENT BY 1 START WITH 1;



/* 
*  S
*  S
*/ 
DROP TABLE S;
CREATE TABLE S (
    S NUMBER(1440) NOT NULL,
 CONSTRAINT PK_S PRIMARY KEY (S)
);

CREATE UNIQUE INDEX idx_S_S ON S (S);

CREATE SEQUENCE Seq_S_S INCREMENT BY 1 START WITH 1;



/* 
*  1440
*  1440
*/ 
DROP TABLE 1440;
CREATE TABLE 1440 (
    1440 NUMBER(1440) NOT NULL,
 CONSTRAINT PK_1440 PRIMARY KEY (1440)
);

CREATE UNIQUE INDEX idx_1440_1440 ON 1440 (1440);

CREATE SEQUENCE Seq_1440_1440 INCREMENT BY 1 START WITH 1;



/* 
*  SY
*  SY
*/ 
DROP TABLE SY;
CREATE TABLE SY (
    SY NUMBER(1440) NOT NULL,
 CONSTRAINT PK_SY PRIMARY KEY (SY)
);

CREATE UNIQUE INDEX idx_SY_SY ON SY (SY);

CREATE SEQUENCE Seq_SY_SY INCREMENT BY 1 START WITH 1;



/* 
*  YO
*  YO
*/ 
DROP TABLE YO;
CREATE TABLE YO (
    YO NUMBER(1440) NOT NULL,
 CONSTRAINT PK_YO PRIMARY KEY (YO)
);

CREATE UNIQUE INDEX idx_YO_YO ON YO (YO);

CREATE SEQUENCE Seq_YO_YO INCREMENT BY 1 START WITH 1;